# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# BLOG SEEDS
# 10.times { |i| Blog.create(title: BetterLorem.w(5, true, false), content: BetterLorem.p(5, false, false), category: i, author: 8) }


# BIO SEEDS
# 31.times { |i| Bio.create(first_name: "Current", last_name: "Employee#{i}", real_title: "Real Title#{i}", funny_title: "Funny Title#{i}", question1: "question1", question2: "question2", question3: "question3", question4: "question4", question5: "question5", answer1: "answer1", answer2: "answer2", answer3: "answer3", answer4: "answer4", answer5: "answer5", bio_pic: "", overview: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sed eum molestias reprehenderit repudiandae ut labore natus expedita magni a adipisci quas maiores, quis accusantium ea amet pariatur, ex repellendus asperiores.") }

# CASE STUDY SEEDS
# 12.times{ |i| Project.create(title: "YMCA Louisville", challenge: "After a record-breaking year for enrollment in 2013, we were challenged by The Greater Louisville YMCA to boost new membership acquisitions and existing member renewals even further the following year.", insight: "While achieving marketing objectives and membership goals is a yearlong process, it's no secret that the four-week membership drive following Christmas is the most critical time. This is when New Year's resolutions are in full swing, and the majority of gyms in the Louisville market are promoting their lowest prices and their newest equipment.", solution: "The Y is already synonymous with healthy living. We needed to reinforce their position of being much more than a typical 'gym and swim' to maximize memberships. That required increased awareness of the Y's social responsibility efforts and youth development initiatives to the key audiences of singles, families and senior citizens. To be successful, we had to convince potential members that the Y's overall community and wellness benefits provided an exceptional value for the monthly price. We developed a comprehensive campaign around the theme, 'Be healthy. Be strong. Belong.' This message clearly conveyed that Y is a place where everyone can come together to improve their physical fitness and contribute to a better community. We brought the line to life by producing a television spot using actual members to illustrate how the Y benefits everyone in the family. Then, we carried our message through print, outdoor and direct mail executions to increase awareness and push promotional membership opportunities. During the peak membership months of January, May and June, we reinforced our traditional media tactics with digital ­search text and display image ads along with paid Facebook posts. We also created a guerilla marketing campaign. Members of the downtown Y staff dressed as – wait for it – gorillas and interrupted high foot-traffic areas with bananas and a message to visit the Y during lunch for a free snack. This helped us break through the clutter and promote downtown memberships directly to our surrounding target audiences.", results: "These tactics – in tandem with the exceptional efforts of the Y's own staff – helped to increase new and renewing household memberships beyond the previous record-breaking year. Specifically, our digital campaign produced results that exceeded our campaign goals, with click-though rates more than 3 times our initial goal and an average cost per click at nearly half of our intended target.", category: i, quote: "As someone who practically grew up at the Y, it is especially fulfilling for me to be a partner in their success.", cite: "Harry Mulkey", logo: "ymca logo path", main_image: "main image path", side_image1: "side image1 path", side_image2: "side image2 path", capabilities: i ) }